Import('*')

SimObject('ExternalMemKernelWorkload.py')
SimObject('ExternalMemFsLinux.py')
SimObject('OutgoingRequestBridge.py')

Source('external_mem_kernel_workload.cc')
Source('outgoing_request_bridge.cc')
Source('sst_riscv_workload.cc')
Source('sst_responder_interface.cc')

DebugFlag('SST')
